# Changes here will be overwritten by Copier
_commit: 94a79d4
_src_path: git@github.com:hvoecking/pypackage-template-private
add_me_as_contributor: false
cli_name: disambiguate
copyright_year: '2026'
documentation: true
email: creator@frankify.app
full_name: Frankify
github_username: frankify-app
has_cli: true
initial_commit: true
is_django_package: false
open_source_license: MIT
open_with_editor: false
package_name: disambiguate
project_name: disambiguate
project_short_description: A tool to resolve markdown glossary terms and their transitive
    dependencies in topological order in a GitHub project or Obsidian vault.
project_slug: disambiguate
run_uv_sync: true
setup_github: false
setup_pre_commit: true

